import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { AppProviders } from "@/components/AppProviders";
import "./globals.css";

// Apple splash screens: iOS picks the one whose media query matches the device exactly.
// Generated by `npm run pwa-assets` (scripts/generate-pwa-assets.mjs).
const SPLASH: { w: number; h: number; dpr: number }[] = [
  { w: 440, h: 956, dpr: 3 }, // 16/17 Pro Max
  { w: 402, h: 874, dpr: 3 }, // 16/17 Pro, 17
  { w: 420, h: 912, dpr: 3 }, // Air
  { w: 430, h: 932, dpr: 3 }, // 14/15 Pro Max, 15/16 Plus
  { w: 393, h: 852, dpr: 3 }, // 14 Pro, 15, 15 Pro, 16
  { w: 390, h: 844, dpr: 3 }, // 12, 13, 14, 16e
  { w: 428, h: 926, dpr: 3 }, // 12/13 Pro Max, 14 Plus
  { w: 375, h: 812, dpr: 3 }, // X, XS, 11 Pro, 12/13 mini
  { w: 414, h: 896, dpr: 3 }, // XS Max, 11 Pro Max
  { w: 414, h: 896, dpr: 2 }, // XR, 11
  { w: 414, h: 736, dpr: 3 }, // 8 Plus
  { w: 375, h: 667, dpr: 2 }, // SE 2/3, 8
];

export const metadata: Metadata = {
  title: { default: "TradeDesk", template: "%s · TradeDesk" },
  description: "Live Pokémon card trade evaluator, multi-language scanner and binder for card shows.",
  applicationName: "TradeDesk",
  manifest: "/manifest.json",
  formatDetection: { telephone: false, address: false, email: false },
  appleWebApp: {
    capable: true,
    title: "TradeDesk",
    statusBarStyle: "black-translucent",
    startupImage: SPLASH.map(({ w, h, dpr }) => ({
      url: `/splash/splash-${w * dpr}x${h * dpr}.png`,
      media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
    })),
  },
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180" }],
  },
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // draw under the notch / Dynamic Island; we pad with env(safe-area-inset-*)
  themeColor: "#0a0c10",
  colorScheme: "dark",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
